import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../pages/components/header'
import Section from './components/Section'
//  import AboutUs from './components/AboutUs'
//  import Careers from './components/Careers'
//import Landing from './components/code-ref/landing-page'
// import Home_demo from './components/code-ref/home-demo'

// import Tables from './components/code-ref/table'
import Footer from './components/code-ref/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
     
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Section/>
      {/* <AboutUs/>
      <Careers/> */}
      {/* <Landing/> */}
      {/* <Home_demo/> */}
      {/* <Tables/> */}
     
      {/* <main className={styles.main}>
        <div className={styles.description}>
        </div>
      </main> */}
      <Footer/>
    </>
  )
}
